apiVersion: wukong.wukong.io/v1alpha1
kind: WukongEnv
metadata:
  name: wukongenv-sample
spec:
  namespaces:
    - 'zadig'
  apps: 
    - name: 'uumiu'
      namespace: 'wukong-operator-system'
      image: 'koderover.tencentcloudcr.com/koderover-public/ingress-nginx-controller:v0.35.0'
      size: 1
      workload: 'Deployment'
      skywalkingBackendAddr: ''
      skywalkingIson: ''

